feat: support uploading local geo data
googleapis/python-bigquery-dataframes pull request #1036
Opened 2024-10-01 21:19 UTC by arwas11

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #308738592 🦕

2024-10-01 22:06 UTC, chelsea-lin commented
The `mypy` tests failed. Could you please help to fix that? `nox -r -s mypy` can help to reproduce tests locally.

2024-10-02 17:59 UTC, chelsea-lin requested changes

2024-10-02 17:59 UTC, chelsea-lin commented on bigframes/session/__init__.py
> +            return None
Please help to add comments here. For example, `An error is thrown for unsupported types, such as geo.`

2024-10-02 18:24 UTC, chelsea-lin approved these changes
Thanks! LGTM

2024-10-18 17:41 UTC, tswast commented
Merging. `doctest` and Samples test failures appear to be unrelated.

2024-10-18 17:42 UTC, merged