docs: document groupby.head and groupby.size methods
googleapis/python-bigquery-dataframes pull request #1111
Opened 2024-10-24 16:20 UTC by arwas11

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
  - `head`: screen/6AwYN3STkX3pS2c
  - `size`: screen/i8BuAneYbS4cTvW, screen/76NHbqGhnUJM53p

Fixes #296390934 🦕

2024-10-30 16:36 UTC, tswast approved these changes

2024-10-30 16:37 UTC, tswast requested changes
Looks good, but it seems doctest is failing. Please fix.

```
FAILED third_party/bigframes_vendored/pandas/core/groupby/__init__.py::groupby.GroupBy.head
FAILED third_party/bigframes_vendored/pandas/core/groupby/__init__.py::groupby.GroupBy.size
```

2024-11-08 20:18 UTC, Genesis929 approved these changes

2024-11-12 17:09 UTC, tswast commented on third_party/bigframes_vendored/pandas/core/groupby/__init__.py
> +              dtype: Int64
Looks like the indentation here is slightly misaligned.

```suggestion
        Compute group sizes.

        **Examples:**

        For SeriesGroupBy:

            >>> import bigframes.pandas as bpd
            >>> bpd.options.display.progress_bar = None

            >>> lst = ['a', 'a', 'b']
            >>> ser = bpd.Series([1, 2, 3], index=lst)
            >>> ser
            a     1
            a     2
            b     3
            dtype: Int64
            >>> ser.groupby(level=0).size()
            a    2
            b    1
            dtype: Int64

        For DataFrameGroupBy:

            >>> data = [[1, 2, 3], [1, 5, 6], [7, 8, 9]]
            >>> df = bpd.DataFrame(data, columns=["a", "b", "c"],
            ...                   index=["owl", "toucan", "eagle"])
            >>> df
                    a  b  c
            owl     1  2  3
            toucan  1  5  6
            eagle   7  8  9
            [3 rows x 3 columns]
            >>> df.groupby("a").size()
            a
            1    2
            7    1
            dtype: Int64
```

2024-11-12 17:09 UTC, tswast approved these changes

2024-11-12 18:08 UTC, merged