fix: use random table when loading data for read_csv, read_json, read…
googleapis/python-bigquery-dataframes pull request #175
Opened 2023-11-06 19:38 UTC by ashleyxuu

…_json

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2023-11-06 20:59 UTC, shobsi approved these changes
LGTM, let's take Tim's LGTM too before submitting

2023-11-07 22:29 UTC, tswast requested changes
Let's wait until after Trevor's PR so that we can make sure to cluster by the correct columns.

2023-11-08 18:58 UTC, tswast requested changes
Please make sure the tables we create are clustered by the native ordering (in cases where we preserve it) and/or the index.

2023-11-09 14:49 UTC, tswast approved these changes
As discussed in chat, we'll update this to do clustering in a future change.

2023-11-09 23:00 UTC, merged

2023-11-10 17:29 UTC, tswast commented on bigframes/session/__init__.py
>          job_config = bigquery.LoadJobConfig()
We forgot to set the table expiration. I can follow-up with a PR.

2023-11-10 18:12 UTC, tswast commented on bigframes/session/__init__.py
>          job_config = bigquery.LoadJobConfig()
https://github.com/googleapis/python-bigquery-dataframes/pull/193