fix: make to_pandas override enable_downsampling when sampling_method is manually set.
googleapis/python-bigquery-dataframes pull request #200
Opened 2023-11-14 01:20 UTC by Genesis929

… is manually set.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes b/310741105

2023-11-14 03:01 UTC, jiaxunwu requested changes

2023-11-14 03:01 UTC, jiaxunwu commented on bigframes/core/blocks.py
> +        sampling_method = sampling_method.lower()
Can you put sampling_method logic together?

2023-11-14 16:04 UTC, Genesis929 commented on bigframes/core/blocks.py
> +        enable_downsampling = bigframes.options.sampling.enable_downsampling
Done.

2023-11-16 22:04 UTC, GarrettWu commented on bigframes/core/blocks.py
> +        max_download_size = (
Nit: less code:

max_download_size = max_download_size or bigframes.options.sampling.max_download_size

2023-11-20 21:05 UTC, Genesis929 commented on bigframes/core/blocks.py
> +        max_download_size = (
Done

2023-11-22 00:31 UTC, GarrettWu approved these changes

2023-11-28 20:51 UTC, jiaxunwu approved these changes

2023-11-28 20:53 UTC, merged