fix: use anonymous dataset to create `remote_function`
googleapis/python-bigquery-dataframes pull request #205
Opened 2023-11-15 01:49 UTC by shobsi

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2023-11-16 01:11 UTC, jiaxunwu requested changes
Any doc changes needed for this?

2023-11-16 07:27 UTC, shobsi commented
> Any doc changes needed for this?

Good call, thanks! Updated README.rst

2023-11-28 18:16 UTC, jiaxunwu approved these changes

2023-11-28 22:31 UTC, tswast approved these changes

2023-11-28 23:42 UTC, merged

2023-11-28 23:44 UTC, shobsi commented
`nox -s e2e` with additional `-k test_remote_` was run locally to verify large remote function tests pass.