fix: LabelEncoder params consistent with Sklearn
googleapis/python-bigquery-dataframes pull request #60
Opened 2023-09-25 21:54 UTC by ashleyxuu

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-dataframes/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2023-09-25 23:21 UTC, GarrettWu commented on bigframes/ml/base.py
> +        y: Optional[Union[bpd.DataFrame, bpd.Series]] = None,
It can't be None.

2023-09-25 23:21 UTC, GarrettWu commented on bigframes/ml/base.py
> +    """A BigQuery DataFrames Transformer base class that transforms data.
More specific only to labels.

2023-09-25 23:55 UTC, GarrettWu requested changes

2023-09-25 23:55 UTC, GarrettWu commented on bigframes/ml/base.py
> +        y: Optional[Union[bpd.DataFrame, bpd.Series]],
remove Optional

2023-09-25 23:57 UTC, ashleyxuu commented on bigframes/ml/base.py
> +        y: Optional[Union[bpd.DataFrame, bpd.Series]],
My bad. Fixed now.

2023-09-26 00:03 UTC, GarrettWu approved these changes

2023-09-26 04:17 UTC, merged